let obj = {
    bairro: "CENTRO",
    capital_social: 50000,
    cep: "77500000",
    cnae_fiscal: 4752100,
    cnae_fiscal_descricao: "Comércio varejista especializado de equipamentos de telefonia e comunicação",
    cnaes_secundarios: '',
    cnpj: "51155445000181",
    codigo_municipio: 9559,
    codigo_municipio_ibge: 1718204,
    codigo_natureza_juridica: 2062,
    codigo_pais: 105,
    codigo_porte: 1,
    complemento: "SALA 02",
    data_exclusao_do_mei: null,
    data_exclusao_do_simples: null,
    data_inicio_atividade: "2023-06-22",
    data_opcao_pelo_mei: null,
    data_opcao_pelo_simples: null,
    data_situacao_cadastral: "2023-06-22",
    data_situacao_especial: null,
    ddd_fax: "",
    ddd_telefone_1: "6392361617",
    ddd_telefone_2: "000000000000",
    descricao_identificador_matriz_filial: "MATRIZ",
    descricao_motivo_situacao_cadastral: "SEM MOTIVO",
    descricao_porte: "",
    descricao_situacao_cadastral: "ATIVA",
    descricao_tipo_de_logradouro: "PRACA",
    email: "CONTATOSMARTPORTO@GMAIL.COM",
    ente_federativo_responsavel: "",
    identificador_matriz_filial: 1,
    logradouro: "DO CENTENARIO",
    motivo_situacao_cadastral: 0,
    municipio: "PORTO NACIONAL",
    natureza_juridica: "Sociedade Empresária Limitada",
    nome_cidade_no_exterior: "",
    nome_fantasia: "SMART",
    numero: "642",
    opcao_pelo_mei: null,
    opcao_pelo_simples: null,
    pais: "BRASIL",
    porte: "MICRO EMPRESA",
    qsa: '[{… }]',
    qualificacao_do_responsavel: 49,
    razao_social: "SMART LTDA",
    situacao_cadastral: 2,
    situacao_especial: "",
    uf: "TO",
}